-- AlterTable
ALTER TABLE `Contract` MODIFY `status` ENUM('PENDING', 'FREELANCER_ACCEPTED', 'CLIENT_ACCEPTED', 'ACTIVE', 'PENDING_REVIEW', 'COMPLETED', 'CANCELLED', 'UNDER_ADMIN_REVIEW') NOT NULL DEFAULT 'PENDING';
